---
sudo: false
language: rust
os:
  - linux
  - osx
dist: trusty
osx_image: xcode9.2
rust: stable
env:
  global:
    - THERMITE_DEBUG_FILENAME: "/tmp/thermite-debug.log"
    - SLUGRUST_RUBY_VERSION: 2.5.3
  matrix:
    - RUBY_STATIC: 1
cache:
  cargo: true
  directories:
    - "$TRAVIS_BUILD_DIR/vendor/bundle"
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
    fi
    rvm install "$SLUGRUST_RUBY_VERSION"
    rvm use "$SLUGRUST_RUBY_VERSION"
    ruby --version
  - bundle install --jobs=3 --retry=3 --path=$TRAVIS_BUILD_DIR/vendor/bundle
before_script:
  - |
    mkdir -p target/debug/deps
    cp $(ruby -e 'puts File.join(RbConfig::CONFIG["libdir"], RbConfig::CONFIG["LIBRUBY_ALIASES"].split(" ").first)') target/debug/deps

script:
  - bundle exec rake spec
  - bundle exec rake thermite:tarball
  - bundle exec rake install
  # yamllint disable
  - if [[ -f "$THERMITE_DEBUG_FILENAME" ]]; then cat $THERMITE_DEBUG_FILENAME; fi
  # yamllint enable
# yamllint disable
deploy:
  - provider: rubygems
    api_key:
      secure: aTwtOlvbrCYKCtgISWXLaT0V2wEHj16fI/8gxckFGrI3rI2c/Z0jAXLNjEkFldu9xPRWIZoFMCnCyy/31Bk3Rb9Sj+QHkwryqr1CHQ+qWm188wlzucjEMh/etz7bEX7I7rPKstuuXgjsw0akb22eXv+EH0pYJqTdNQ9G7ii/PEWdgjP/InsKmUz3PbJ2Oomk/LcIR07dfDZZNpPJgLQYEOkl7rnse92Wdw9gncusDQuIafnpl6Bf7Rd4Jhx9C3yKbVYFfW9MGkYBhATiV9VKqBm5VnhbeOanUQLRLeS+KesaTX8g8qgV9eb4jZhiKgZ0dLjSEbbPPg0DsKp+ZqKJXXkkBbLeql25q6AwskYHo8oe8C8VcIZHFzEFY6MIUp3h0v135UnCVtKM0iBHA9u+tzMWqZmpwcWQoxsV2F+jHE5plh1y0rkQ3PvANlxgJn4pbSc6Upo34ApjYPgNSmp5Y6YRIrIKeWrKMPtA98ehTCJ4Itx9Ugez/BHEj63dXfjjEpT2cjI8sT8Fk4mEmPYdRQKZJpy1bQX27VnISgBK1uMHnppxXooI8xaS0nqnTwoIfEc6JzQZekuy+gHxnpS1PHjo6PzmbKJgYgWpD39ue7TrDOoQgAba1hNccF0BjgnCvg9lPEy9n68h+ULbjXtzsxiAk+hlka0km/Ecq26rcnc=
    gem: slugrust
    on:
      branch: master
      repo: ianks/slugrust
      tags: true
  - provider: releases
    api_key:
      secure: LNixPblWwpLtpsI6Aa0bcwYrGKs6wtJknvQ5ZZN+H7WBWHg9DXPk4fWYu04aoRLhmxnElv49bk5YgyIF6xGJpbhglMh8W/Y+JHhp6B1Oey/SK5VE/TCsno4eQTpKCVQCbfF0WYCEjHO6ym8jgTeqqJclSkzCXEMHaTzSc555+N86zIuT5xuVi6n0v9OpLVHEuEJ9hOAsCOiCetvUEsOeaqEVbO+BmJlpmmTKjPM1tgmMLUA15c6WblwpeU6FsVIkcdnvPxLjHR3C0+jVYnvdZFddSnL6bKIHjsAoWlEPz/lzkpUWrL1sz200aHnm3YI+WT+apuj7NxkOb1tocECLJ75WV07byCIGFRTPygZQnZhhhq8LZQxl7lcJZ0FocK4r4AE/fJTzflU5MLUvxEYzubulVlniKQFAkiiECWlH6eQEVLBGsPqEQylhGAMchzSMPqswAw6gwjv/TpJPhMJUtqvCPIRzpq/JNSpNZJ1sb6b+ZEfN/e6u/f9BAaLUclfiewzhNyaq1Nm08pEBhw1+OyhZ9SdFHzQG8Uy0MnP+kqBfYwMeDz1WmuA4h6kgagHyNk9Ik/Whvk/NqZzuEceFbaVUPa0v+ilNlZN98LtWaMsaum5R7JhBjsrovf1oxGB8cQE1eP2GbccBbmBCW+ZYtRhkTEpnK69Or1aW5MqN0M4=
    file: slugrust-*.tar.gz
    file_glob: true
    skip_cleanup: true
    on:
      branch: master
      repo: ianks/slugrust
      tags: true
# yamllint enable
